Interpreter Redesign
niklas-simon/PI22_Brainfuck-Interpreter pull request #1
Opened 2024-09-22 15:43 UTC by niklas-simon

Complete redesign of Interpreter, because before it was full of jank and far too complicated. Also this one is documented.

2024-09-24 15:49 UTC, ba-lindner requested changes
Alte Infos in README sollten noch aktualisiert werden

2024-09-24 15:49 UTC, ba-lindner commented on README.md
nicht bearbeiteter Teil beinhaltet noch alte Informationen zum I/O-Port:
- in Anforderungen -> Interpreter: 10 pin
- in Anforderungen -> I/O Management & Digital Twin: 18 pin

2024-09-24 18:23 UTC, niklas-simon commented on README.md
Dokumentation wurde aktualisiert.

2024-09-25 05:59 UTC, ba-lindner approved these changes
Sieht gut aus

2024-09-25 05:59 UTC, merged